### ISSUE TITLE
Stop "Show recap" popup

### ISSUE THREAD

**Issue by jjspace** [Kouzukii/ffxiv-deathrecap#11]
Would you be able to add an option to Death Recap to prevent the little "Show recap" button from popping up?
Or maybe also an option to only have it pop up for your own deaths?
It's getting distracting progging savage and seeing it pop up every time someone else dies. Many times I die or someone else does I already know what happened and don't need the recap. Personally I'd like an option to not have the popup at all and use `/dr` only when I want to check in on what happened when I died.

**Comment by Kouzukii** [comment]
The latest version has a config menu where you can change this.
