### ISSUE TITLE
Killing blow no longer present

### ISSUE THREAD

**Issue by munsta0** [Kouzukii/ffxiv-deathrecap#12]
Up until a few days ago, I could see the killing blow in death recap, now it shows everything leading up to it. Not sure what changed.

See example : https://puu.sh/ITCUq/5fc50155d5.png

**Comment by Kouzukii** [comment]
The HP column always shows your HP before the damage was applied, so in this case you died to the 57k damage from Hesperos' Fire IV.
Most attacks have animations however, so even though the table lists it as 2.6s before your death, the damage was snapshotted and you died after the animation finished.
