### ISSUE TITLE
Death Recap 6.1 Update PR

### ISSUE THREAD

**Issue by rootdarkarchon** [Kouzukii/ffxiv-deathrecap#13]
Hi,

the PR for the Death Recap has Api Level still on 5 (instead of 6) and won't allow to be downloaded with the testing version of Dalamud.

Thanks for your hard work!

**Comment by Kouzukii** [comment]
Ah I'd just assumed it'd be backwards compatible like before. Thanks for the notice, I'll have a look

**Comment by Kouzukii** [comment]
Should be fixed now
