### ISSUE TITLE
Untranslated ability

### ISSUE THREAD

**Issue by Kurochi51** [Kouzukii/ffxiv-deathrecap#16]
In Ultima's Bane (Unreal), one of the abilities that the boss uses is in japanese
![kLVZsQm](https://user-images.githubusercontent.com/5596521/169707325-2923c770-cbfe-402a-8631-45e5ede669ea.png)

**Comment by Kouzukii** [comment]
Most boss auto-attacks are not translated, because their name never shows up in game. It just says `16796 damage` in the event log and floating combat text

**Comment by Kouzukii** [comment]
I could try to distinguish between auto-attacks and named attacks and change the wording in that case, I'll have a look at it.

**Comment by Kouzukii** [comment]
Fixed in the latest version
