### ISSUE TITLE
Does nothing since patch 6.11a

### ISSUE THREAD

**Issue by Brasolis** [Kouzukii/ffxiv-deathrecap#18]
Since the latest 6.11a patch the plugin does not track anything for me. I have used the "Reset plugin settings & reload" option as well as manually deleting the plugin from my appdata folder and reinstalling but the behavior doesn't change.

I have seen some other players with the same issue in the goat place discord.

My installed plugins:
Browsingway
BDTH
Chat Bubbles
Currency Alert
DailyDuty
Damage Info
DeathRecap
Discord Rich Presence
EnemyListDebuffs
Engage Timer
ezMiniCactpot
Fancy Loading Screens
Gatherbuddy
Glamaholic
Globetrotter
Housemate
Item Search
Kapture
Macro Chain
NeatNoter
NoSoliciting
Orchestrion
PartyIcons
Pat Me
Peeping Tom
Penny Pincher
PingPlugin
Pixel Perfect
PlayerTrack
PriceCheck
ReadyCheckHelper
Redirect
Simple Tweaks
Sonar
Triad Buddy
WaymarkPresetPlugin

If there is any other logs or info that would be helpful let me know!

**Comment by Kouzukii** [comment]
6.11a updated the games opcodes, I have released a fix under testing (enable experimental plugins in dalamud settings)
I'll publish the version into stable later today.

**Comment by Brasolis** [comment]
Ah, thank you for the response. I had raid members using this last night fine so I assumed it may have been a new conflict but I guess they just have testing on!
