### ISSUE TITLE
Endwalker Update?

### ISSUE THREAD

**Issue by Digawen** [Kouzukii/ffxiv-deathrecap#2]
Can we hope for an endwalker update?
I would be very happy about that.

**Comment by Kouzukii** [comment]
I've been busy playing through the story, but I'll update it asap after that

**Comment by Digawen** [comment]
Thank you very much, sir.

**Comment by MarkusWo** [comment]
hey, any updates on the update :-D

**Comment by haojunsui** [comment]
I updated this plugin for 6.0x support https://github.com/haojunsui/ffxiv-deathrecap

Let me know if you want to me submit a pull request as well

**Comment by Kouzukii** [comment]
Thanks for the work @haojunsui 

I hope you don't mind I've used your updated opcodes and structs to update and overhaul the plugin for endwalker.

![image](https://user-images.githubusercontent.com/11648852/150708829-28798697-34a9-4fbc-9992-9bdf703354a2.png)
