### ISSUE TITLE
User confusion on official Dalamud Plugins repo

### ISSUE THREAD

**Issue by reiichi001** [Kouzukii/ffxiv-deathrecap#20]
Hello!

This is Franz from the official XIVLauncher/Dalamud support server (aka goatplace). We've been seeing an increased amount of feedback by DeathRecap users because only the testing branch has received a version with 6.15 compatible opcodes.

I've opened https://github.com/goatcorp/DalamudPlugins/pull/2649 to move the test version over to stable, consolidating it into a single release, but would like your confirmation to merge first. Or if you'd prefer to keep it testing only, we can alternatively block the outdated stable version.

**Comment by Kouzukii** [comment]
Oh apologies, I completely forgot to move it into stable. Go ahead
