### ISSUE TITLE
about ActorControlCategory 

### ISSUE THREAD

**Issue by tssailzz8** [Kouzukii/ffxiv-deathrecap#21]
https://github.com/Kouzukii/ffxiv-deathrecap/blob/a0350692b04e85817965415137995c48a9f03c7c/Messages/ActorControlCategory.cs#L3
this is changed in 6.1 https://github.com/ravahn/machina/commit/c59b530528b5fa8e3b2cefd527cc7aa19ae033e6

**Comment by Kouzukii** [comment]
I've not published the latest opcode changes for 6.15 on GitHub. I'm currently planning to move away from opcodes and instead hook the functions for each packet directly.

**Comment by tssailzz8** [comment]
it not opcodes

**Comment by Kouzukii** [comment]
Oh I see they split hot and dot

**Comment by Kouzukii** [comment]
now fixed in latest testing build
