### ISSUE TITLE
i think we can get the Shield before dead

### ISSUE THREAD

**Issue by tssailzz8** [Kouzukii/ffxiv-deathrecap#24]
like this https://github.com/Caraxi/SimpleTweaksPlugin/blob/64457fa622a31367ff0bb179da9eb1f1f5733fc5/Tweaks/UiAdjustment/ShowShieldOnHPBar.cs#L118,or we use hook to do this

**Comment by Kouzukii** [comment]
that's what I'm already doing: https://github.com/Kouzukii/ffxiv-deathrecap/blob/master/Extensions.cs#L15

I'm not sure how a hook would help.
