### ISSUE TITLE
[Feature Request] Collapse overlay.

### ISSUE THREAD

**Issue by dawnbomb** [Kouzukii/ffxiv-deathrecap#26]
Many plugins now have a down arrow next to the X button, you can click to disappear everything except the name bar, the down arrow, and the close button.

This is useful for a clean UI, so users can see the death recap only when they want to, without typing /deathrecap and also useful for people using various other mods, or overloaded controller users who lack space for a chat macro to open it.

**Comment by Kouzukii** [comment]
Sure, I'll add it in the next release.
