### ISSUE TITLE
[Feature Requests] Tracking Reprisal, Feint and Addle, checkbox to open window on death

### ISSUE THREAD

**Issue by bladehawkz** [Kouzukii/ffxiv-deathrecap#3]
As title states:

Tracking Reprisal, Feints and Addle which are debuffs on the enemy (typically a boss) can help identify mitigation issues more.

Also, a checkbox to open the window on death could help, sometimes I don't want the window to open every time I die.

Beyond that, I think the functionality is very good and will eventually end up as a better replacement to cactbot's oopsydaisy :)

**Comment by Kouzukii** [comment]
Good ideas! I've added addle, feint and reprisal tracking.
I'll add a hide function in the next update

**Comment by rushtothesun** [comment]
I agree, it's very well made. With party death tracking it would replace oopsydaisy.

**Comment by Kouzukii** [comment]
Instead of the full window, a small popup window will open instead now that you can put on the side of your screen.
