### ISSUE TITLE
M4S not counting incoming damage

### ISSUE THREAD

**Issue by 0ShinyNinetales0** [Kouzukii/ffxiv-deathrecap#38]
On M4S fight, DeathRecap does not show any incoming damage apart from Auto-Attacks to tank. Tried reinstalling, sadly no use. Other fights work properly

**Comment by 0ShinyNinetales0** [comment]
My bad, checked multiple times now. Think only damage shows that comes straight from the boss (raidwides, autos, etc) but not other stuff. Still not sure if shows as intended

**Comment by Kouzukii** [comment]
this should've been fixed by yesterday's dalamud release. Have you restarted your game?

**Comment by 0ShinyNinetales0** [comment]
Yeah I have restarted and sadly it still is this way! I noticed the issue yesterday and today I rebooted twice and it did not help, also as mentioned before reinstaling the plugin did not work for me

**Comment by 0ShinyNinetales0** [comment]
Somehow it seems to be fixed now, I deleted my dalamud config file and reinstalled the plugin then!
