### ISSUE TITLE
Why does the recap often show events after death. Am i misunderstanding it?

### ISSUE THREAD

**Issue by CatbotTsumi** [Kouzukii/ffxiv-deathrecap#39]
I've had several instances where the deathrecap shows attacks after the character already died.
In this example the player was overkilled at the 5th event down (-4s)
![ffxiv_dx11_sI8uwIlkJH](https://github.com/user-attachments/assets/1574f68b-1189-4758-9fe7-b25ff9a0f0fc)
It shows on both views
![ffxiv_dx11_QyoaB43S1k](https://github.com/user-attachments/assets/7f33ae0d-d29e-4957-a375-2621c0364dae)

Is this intentional? if so, why does this happen?

**Comment by Kouzukii** [comment]
This is unfortunately just how the game processes damage events. The animation of final sting takes 4 seconds to play, the damage however is already recorded as soon as the bee finishes casting it. DeathRecap records events as they are snapshot by the server. Say if you used a lot of mitigation before you died, even though the damage number has not appeared yet on your screen the bee finished casting before you used your mitigation (that is how it will appear in the death log) and the damage will be applied unmitigated.

**Comment by Kouzukii** [comment]
so even if it feels counter intuitive to see the damage numbers not as they showed on your screen, this way you'll be able to tell if you died because mitigation / healing was applied too late (after the server snapshot the damage)

**Comment by CatbotTsumi** [comment]
A bit confusing, but at least theres a proper reason for it. Thanks for the explanation!
