### ISSUE TITLE
Crash when dragging the Deathrecap window to the side

### ISSUE THREAD

**Issue by rushtothesun** [Kouzukii/ffxiv-deathrecap#4]
If I drag the window to the right side where more than 75% of the window is off screen it'll crash the game.

**Comment by rushtothesun** [comment]
If the Enable multi-monitor windows setting is checked in Dalamud settings the crash doesn't happen but if someone doesn't use that setting it'll crash.

**Comment by Kouzukii** [comment]
I don't know why you would do this, but I've fixed the crash anyways :D
