### ISSUE TITLE
[Feature Request] Chat notice alternative to popup box

### ISSUE THREAD

**Issue by gucciBane** [Kouzukii/ffxiv-deathrecap#6]
I think it could be pretty unobtrusive but also sufficiently remindery if there was an alternative option to the popup box, where a link just popped up in chat after a death/wipe, maybe akin to 'view death report.'

**Comment by Kouzukii** [comment]
This is a good idea. I'll add an option for this in the next release.

**Comment by gucciBane** [comment]
Awesome, thank you!

**Comment by Kouzukii** [comment]
Took a while, but 1.6.0 finally allows you to customize the popup.
