### ISSUE TITLE
[Bug] Non-party members included in recap

### ISSUE THREAD

**Issue by FFXIVWytes** [Kouzukii/ffxiv-deathrecap#7]
Hi,

I've noticed at hunts that it will pick up non-party members in the recap window. I think this is probably due to the sheer amount of data in the log during hunts so I'm not sure if there's any way to solve it but wanted to let you know.

Thanks!

**Comment by Kouzukii** [comment]
This is actually intended, it will however always display your party members at the top of the list

**Comment by FFXIVWytes** [comment]
It would be nice if that was an option! I sometimes randomly get deaths in the area from people who used self-destruct nearby 😄

**Comment by grinkgo** [comment]
Definitely needs some more customization options to reduce spam

**Comment by Dedoooo** [comment]
> I tested it a few times in frontline, but if the amount of playernames is overwhelming I could maybe add an option to only display current party members

please do this and a condition to only duties!

**Comment by Kouzukii** [comment]
You can customize this to your preference in 1.6.0
